"""
Unit tests for the pairwise permutation-test engine (05-02, REV-04/F6 Q3).

The engine under test is ``script/permutation_tests.py``: pairwise model
comparisons on the aggregate view — per-task zscore vectors aligned on each
pair's common task set, ``scipy.stats.permutation_test`` with
``permutation_type="samples"`` (score-vector permutation across tasks,
D-17/OQ5), 10,000 shuffles, ``rng`` seeded (T-05-05: reproducibility is the
integrity control), and BH correction over the pair family via
``scipy.stats.false_discovery_control``.

Tests run against small synthetic score matrices (D-09: synthetic tests
never substitute for real data; the committed 861-pair artifact is validated
by ``tests/test_schemas.py`` and regenerated by ``make data``):

- 3 models -> exactly C(3,2)=3 pairs; adjusted p-values equal the
  hand-computed Benjamini-Hochberg step-up over the raw p-values
- a pair with zero common tasks is excluded from the family and disclosed
- two independent runs are byte-identical (determinism truth)
- the CLI mirrors export_runs.py's REPO_ROOT-relative argparse

See also:
    - ``tests/test_aggregation.py`` — the tie rule + weighted-score units.
    - ``tests/test_vendored_stats.py`` — the statistical vocabulary source.
"""

import json

import pytest
from permutation_tests import build_artifact, main, write_artifact

# A 3-model matrix: m-high separates cleanly from both others; m-twin hugs
# m-mid (no separation). Values are per-task zscores over a common task set.
MATRIX = {
    "m-high": {"t1": 2.0, "t2": 2.1, "t3": 1.9},
    "m-mid": {"t1": 0.1, "t2": 0.0, "t3": 0.2},
    "m-twin": {"t1": 0.1, "t2": 0.05, "t3": 0.15},
}

# Fast-lane resample count for unit tests; the production default (10,000)
# is disclosed in the artifact's info block and used by `make data`.
N_RESAMPLES = 2000


def _bh_stepup(raw):
    """Hand-computed Benjamini-Hochberg step-up over ascending raw p-values.

    ``adj[k] = min over k' >= k of min(1, raw[k'] * n / (k'+1))`` — the
    manual formula, independent of scipy's ``false_discovery_control``.

    Args:
        raw: Raw p-values in ASCENDING order.

    Returns:
        Adjusted p-values, same order (monotone non-decreasing).
    """
    n = len(raw)
    out = [0.0] * n
    running = 1.0
    for i in range(n - 1, -1, -1):
        running = min(running, raw[i] * n / (i + 1))
        out[i] = min(1.0, running)
    return out


def test_three_models_yield_three_pairs_with_hand_computed_bh():
    """C(3,2)=3 pairs; the artifact's p_adj values equal the hand-computed BH
    step-up over the artifact's own raw p-values, the separated pairs are
    significant at FDR 0.05, and the twin pair is not."""
    artifact = build_artifact(MATRIX, n_resamples=N_RESAMPLES, seed=42, batch=100)

    assert len(artifact["pairs"]) == 3
    assert artifact["info"]["family_size"] == 3
    assert artifact["info"]["n_resamples"] == N_RESAMPLES
    assert artifact["info"]["seed"] == 42

    by_pair = {(p["model_a"], p["model_b"]): p for p in artifact["pairs"]}
    assert set(by_pair) == {
        ("m-high", "m-mid"),
        ("m-high", "m-twin"),
        ("m-mid", "m-twin"),
    }
    raw = sorted(p["p_value"] for p in artifact["pairs"])
    expected = _bh_stepup(raw)
    got = sorted(p["p_adj"] for p in artifact["pairs"])
    assert got == pytest.approx(expected, rel=1e-12)

    # Direction: the clearly separated pairs are significant; the twin pair
    # (near-identical score vectors) is not.
    for pair in (("m-high", "m-mid"), ("m-high", "m-twin")):
        assert by_pair[pair]["significant"] is True
        assert by_pair[pair]["n_common_tasks"] == 3
    assert by_pair[("m-mid", "m-twin")]["significant"] is False


def test_zero_common_task_pair_excluded_and_disclosed():
    """A pair sharing no task cannot be permuted: it is excluded from the BH
    family and disclosed under ``info.excluded_pairs``."""
    matrix = {
        "m-a": {"t1": 1.0, "t2": 0.5},
        "m-b": {"t1": 0.9},
        "m-c": {"t2": 0.4},
    }
    artifact = build_artifact(matrix, n_resamples=500, seed=42, batch=100)

    tested = {(p["model_a"], p["model_b"]) for p in artifact["pairs"]}
    assert ("m-b", "m-c") not in tested
    assert tested == {("m-a", "m-b"), ("m-a", "m-c")}
    assert artifact["info"]["family_size"] == 2
    assert artifact["info"]["excluded_pairs"] == [
        {"model_a": "m-b", "model_b": "m-c", "reason": "zero common tasks"}
    ]


def test_artifact_is_byte_deterministic(tmp_path):
    """Two independent runs over the same matrix produce byte-identical
    artifact files (sorted iteration, sort_keys, seeded rng) — REV-04
    precision: the permutation artifact regenerates byte-identically."""
    first = build_artifact(MATRIX, n_resamples=N_RESAMPLES, seed=42, batch=100)
    second = build_artifact(MATRIX, n_resamples=N_RESAMPLES, seed=42, batch=100)
    assert first == second

    write_artifact(first, tmp_path / "run1.json")
    write_artifact(second, tmp_path / "run2.json")
    assert (tmp_path / "run1.json").read_bytes() == (tmp_path / "run2.json").read_bytes()
    # The emitted JSON is canonical: parse round-trips identically too.
    doc = json.loads((tmp_path / "run1.json").read_text(encoding="utf-8"))
    assert set(doc) == {"info", "pairs"}


def test_cli_help_exits_zero(capsys):
    """``--help`` exits 0 (argparse) and the usage block names the
    REPO_ROOT-relative default paths."""
    with pytest.raises(SystemExit) as exc:
        main(["--help"])
    assert exc.value.code == 0
    assert "--input-dir" in capsys.readouterr().out
